// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdG1v4Rt2KPeGOw6M6HCgELseeUH3kr24',
    appId: '1:688047117260:web:6ec06ceafba2856d52c369',
    messagingSenderId: '688047117260',
    projectId: 'helpcircle-888c6',
    authDomain: 'helpcircle-888c6.firebaseapp.com',
    storageBucket: 'helpcircle-888c6.firebasestorage.app',
    measurementId: 'G-SKLG7W7N3N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJbysDEzyCqWgFuES4iwvD6OQ-a-r1vIQ',
    appId: '1:688047117260:android:5a0d5552d63e0b3952c369',
    messagingSenderId: '688047117260',
    projectId: 'helpcircle-888c6',
    storageBucket: 'helpcircle-888c6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtLNw7YZK0zjtfxRsSaGEgPOpQJARoXIQ',
    appId: '1:688047117260:ios:7fd304f42f61611f52c369',
    messagingSenderId: '688047117260',
    projectId: 'helpcircle-888c6',
    storageBucket: 'helpcircle-888c6.firebasestorage.app',
    iosBundleId: 'com.example.helpCircleNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtLNw7YZK0zjtfxRsSaGEgPOpQJARoXIQ',
    appId: '1:688047117260:ios:7fd304f42f61611f52c369',
    messagingSenderId: '688047117260',
    projectId: 'helpcircle-888c6',
    storageBucket: 'helpcircle-888c6.firebasestorage.app',
    iosBundleId: 'com.example.helpCircleNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdG1v4Rt2KPeGOw6M6HCgELseeUH3kr24',
    appId: '1:688047117260:web:6e1f38a19f99a25352c369',
    messagingSenderId: '688047117260',
    projectId: 'helpcircle-888c6',
    authDomain: 'helpcircle-888c6.firebaseapp.com',
    storageBucket: 'helpcircle-888c6.firebasestorage.app',
    measurementId: 'G-QGQZ9YS238',
  );

}